# Generated by Django 4.1.7 on 2023-04-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SotibOlish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('count', models.PositiveBigIntegerField()),
                ('narx', models.PositiveBigIntegerField()),
                ('all_sum', models.PositiveBigIntegerField()),
            ],
        ),
    ]
