# Generated by Django 4.1.7 on 2023-04-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sotibolish',
            options={'ordering': ['id'], 'verbose_name': 'Sotib olish', 'verbose_name_plural': 'Sotib olish'},
        ),
        migrations.AlterField(
            model_name='sotibolish',
            name='all_sum',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
    ]
