# Generated by Django 4.1.7 on 2023-04-09 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_sotibolish_options_alter_sotibolish_all_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='sotibolish',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
